

def add_num(num1,num2):
    return num1 + num2



try:

    print(add_num(1,2))

except:
    print (' an error!')
else:
    print('all went well')

print('something happened!')